apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway
  labels:
    communication-layer: api-gateway
spec:
  replicas: 1
  selector:
    communication-layer: api-gateway
  template:
    metadata:
      labels:
        communication-layer: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ${IMG}
        command: ["/usr/bin/java"]
        args: ["-jar", "/jar/APIGateway.jar", "-l", "debug"]
---

apiVersion: v1
kind: Service
metadata:
  labels:
    communication-layer: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8080
    name: port-8080
  selector:
    communication-layer: api-gateway
